version: '3'
services:
  wordpress:
    container_name: wordpress
    image: wordpress:4.9.8
    ports:
     - "80:80"
    env_file: .env
    volumes:
     - "./data:/var/www/html/:rw"
  ftp:
    container_name: ftp
    build:
      dockerfile: Dockerfile/vsftpd
      context: .
    ports:
      - "20:20"
      - "21:21"
      - "12000-12100:12000-12100"
    env_file: .env
    volumes:
     - "./conf/vsftpd:/etc/vsftpd:ro"
     - "./data:/var/www/html/:rw"
     - "./conf/pam.d/vsftpd:/etc/pam.d/vsftpd:ro"
     - "./users/vsftpd:/tmp/vsftpd.passwd:ro"
    command: vsftpd -opasv_address=${FTP_PASV_ADDRESS} -opasv_addr_resolve=${FTP_ADDRESS_RESOLVE} /etc/vsftpd/vsftpd.conf