version: '3'
services:
  database:
    container_name: database
    restart: always
    image: mysql:5.7
    ports:
     - "3306:3306"
    volumes:
     - "./volumes/database:/var/lib/mysql:rw"
    environment:
     MYSQL_USER: ${WORDPRESS_DB_USER}
     MYSQL_PASSWORD: ${WORDPRESS_DB_PASSWORD}
     MYSQL_RANDOM_ROOT_PASSWORD: "yes"
     MYSQL_DATABASE: ${WORDPRESS_DB_NAME}
  wordpress:
    container_name: wordpress
    restart: always
    image: wordpress:${WORDPRESS_VERSION}
    ports:
     - "80:80"
    env_file: .env
    volumes:
     - "./volumes/wordpress:/var/www/html/:rw"
    depends_on:
     - database
    links:
     - database
  ftp:
    container_name: ftp
    restart: always
    build:
      dockerfile: Dockerfile/vsftpd
      context: .
    ports:
      - "20:20"
      - "21:21"
      - "12000-12100:12000-12100"
    env_file: .env
    volumes:
     - "./conf/vsftpd:/etc/vsftpd:ro"
     - "./volumes/wordpress:/var/www/html/:rw"
     - "./conf/pam.d/vsftpd:/etc/pam.d/vsftpd:ro"
     - "./users/vsftpd:/tmp/vsftpd.passwd:ro"
    command: vsftpd -opasv_address=${FTP_PASV_ADDRESS} -opasv_addr_resolve=${FTP_ADDRESS_RESOLVE} /etc/vsftpd/vsftpd.conf